### ISSUE TITLE
Consuming Swagger as an alternative to compiled specs

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/ARMExplorer#10]
As I understand, for [Swagger](http://swagger.io/), we just get a JSON file that describes the API. Then the idea is that the same model we use today can be produced from that JSON. Then the rest is identical.

**Comment by matt-gibbs** [comment]
Yes, there is a new modeler that consumes Swagger and populates the same in-memory model. Only supports generic Swagger at this point. ARM-specific extensions are being added shortly.

**Comment by sergey-tihon** [comment]
Does `swagger.json` available for users somewhere?

**Comment by davidebbo** [comment]
Not yet, but hopefully that'll be coming soon!

**Comment by shobak101** [comment]
support done and Microsoft.Web is now consumed from a swagger file
