### ISSUE TITLE
Cannot select a subscription in dropdown

### ISSUE THREAD

**Issue by rgardler** [projectkudu/ARMExplorer#109]
I have a number of subscriptions but I can only see one of them in the ARMExplorer interface. There is a drop down which looks like it should allow me to select a subscription, but it only has a single subscription in it.

**Comment by davidebbo** [comment]
The drop down is to selected AAD directory, not subscription. Select the proper directory first, and then expand the tree to see the subscriptions for that tenant.

**Comment by rgardler** [comment]
Doh! Of course, I see the nice clear "Subscriptions" on the right now. I blame my pre-coffee mind. Thanks.
