### ISSUE TITLE
Remove hard coded references to specific specs

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/ARMExplorer#11]
Right now, we have hard coded references ([here](https://github.com/projectkudu/ARMExplorer/blob/156201e7908c517905fa69391095bde299da95d1/Controllers/OperationController.cs#L29-L32)). Would be nice to move away from that so it's just a drop in model.

And later, it will be a drop in model based on Swagger (per #10).

**Comment by ahmelsayed** [comment]
specs can be dropped in `~\HydraSpecs` and will be loaded dynamically

**Comment by davidebbo** [comment]
Very cool! Those I do wish the specs were not part of this repo, and instead be something we manage separately, like the Try packages.

**Comment by ahmelsayed** [comment]
Sure, I think I'll also move the directory under App_Data
