### ISSUE TITLE
Add support for cancelling and deleting ARM deployments

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/ARMExplorer#110]
Cancelling is done via a POST on `.../deployments/MyDeployment/cancel`, and deleting is just DELETE on `.../deployments/MyDeployment`.

Cancelling is pretty useful when something gets stuck, and I don't think there is any Portal support to do it. I usually end up using ARMClient, which is painful.

**Comment by davidebbo** [comment]
@stuartleeks this is right up your alley if you have cycles :)

**Comment by stuartleeks** [comment]
Ah yes, that would be nice!
