### ISSUE TITLE
Unable to see dashboard list and properties for Microsoft.Portal 

### ISSUE THREAD

**Issue by newmarketliz** [projectkudu/ARMExplorer#113]
Fantastic utility!  Is there a way to get to my dashboards?  TY!

**Comment by davidebbo** [comment]
Not sure I understand the question. What dashboard are you referring to? Resource Explorer is about drilling through the ARM API.

**Comment by newmarketliz** [comment]
Hi David,

I’m guessing this may just not be supported yet for Application Insights dashboards… but when I enter the word “dashboard” in the search box it does resolve with a drop-down and a tooltip for my configured dashboards:

[cid:image002.jpg@01D1B2AB.324B1C30]

But I’m unable to retrieve this information in the tree to the left.

Thank you for the quick response!

All the best,
Liz

**Comment by davidebbo** [comment]
Your image didn't make it. What specific ARM path are you trying to access?

**Comment by newmarketliz** [comment]
Here’s a tooltip snippet through inspector:

<li class="list-group-item ng-binding ng-scope" ng-repeat="item in resourceSearchModel.suggestions" ng-click="selectResourceSearch(item)" title="/subscriptions/5386d6f9-5e7b-4139-a9b5-52a949b56424/resourceGroups/dashboards/providers/Microsoft.Portal/dashboards/4816f7a4-487d-4ce1-8caf-da3e2140c2e4">
                            4816f7a4-487d-4ce1-8caf-da3e2140c2e4<small class="ng-binding">(Microsoft.Portal/dashboards)</small>

**Comment by davidebbo** [comment]
Looks like your comment got corrupted. Please make sure to write your comments directly on the GitHub web interface, as email does not work well. Thanks!

**Comment by newmarketliz** [comment]
Will do!   Really appreciate your quick response.  TY!!

**Comment by newmarketliz** [comment]
This is the path provided for the dashboard in the tooltip and all three appear in the search drop-down as expected:

/subscriptions/5386d6f9-5e7b-4139-a9b5-52a949b56424/resourceGroups/dashboards/providers/Microsoft.Portal/dashboards/4816f7a4-487d-4ce1-8caf-da3e2140c2e4

We're hoping to rollout dashboards across several environments that will match in configuration and vary by filters.

Thank you!

**Comment by davidebbo** [comment]
Thanks the ARM path helps. I have not encountered this `Microsoft.Portal` resource provider. Do you have a pointer to more information about what it's about?

I think we would need to add this to our provider list in Resource Explorer for it to show up with basic support.

**Comment by davidebbo** [comment]
Closing as this went dry.
