### ISSUE TITLE
Microsoft.Web/sites/{ResourceName}/hybridconnection has no PUT Method

### ISSUE THREAD

**Issue by initparam** [projectkudu/ARMExplorer#119]
One cannot edit the configuration of the HybridConnection  under Microsoft.Web/sites/{ResourceName}/hybridconnection
The "Powershell" tab shows with syntax error regarding that the resource name shows twice in the command.
I have tried using PUT on the Page, and using Rest, and New/Set-AzureRMResource but i get that the HTTP Method PUT is not supported. is this a BUG? or is this Object not editable as of now? if such, when will this be possible?

**Comment by davidebbo** [comment]
I would suggest trying with ARMClient, which is a lower level tool. If you can't do a PUT using it, then it establishes that this is not a Resource Explorer issue, but is an API issue.

**Comment by snobu** [comment]
Here are the REST APIs for that:
https://msdn.microsoft.com/library/azure/dn232347.aspx

e.g. to Create or Update a Hybrid Connection:
https://msdn.microsoft.com/en-us/library/azure/dn743828.aspx

    PUT https://management.core.windows.net/{subscription-id}/cloudservices/{cloud-service-name}/resources/biztalkservices/~/biztalk/{biztalk-service-name}/hybridconnection/{hybrid-connection-name}

If you've already tried calling those, what was the exact error response?

**Comment by snobu** [comment]
BTW: By the look of things these aren't Web App Hybrid Connection (as you find them in Azure App Service) but BizTalk stuff. Most probably Web App HCs don't expose REST APIs.. yet.

**Comment by initparam** [comment]
Thank you for the update guys.
What we are trying to achieve here is to Connect/configure an existing WebApp to use an already created HybricConnection via REST or some other method because the only way to make use of the HybridConnection is via the Portal (ref. these concepts https://azure.microsoft.com/nb-no/documentation/articles/web-sites-hybrid-connection-get-started/ and https://azure.microsoft.com/en-us/documentation/articles/web-sites-hybrid-connection-connect-on-premises-sql-server/)

Because im using VSTS to release deployment of our environments i need to configure HC on the WebApp.

I Hope im making sense?

@davidebbo the ARMClient also says that PUT is not supported also.
```
armclient PUT subscriptions/xxxxx/resourceGroups/xxxx/providers/Microsoft.Web/sites/xxx/hybridconnection?api-version=2014-11-01 "{properties: { entityName: 'xxxx', entityConnectionString: 'xxxx', resourceType :'', resourceConnectionString: '', hostname: 'xxxx', port: 80, biztalkUri: '/subscriptions/xxxxxxx/resourceGroups/xxxx/providers/Microsoft.BizTalkServices/BizTalk/elkitdsdev/HybridConnection/xxxxx }}"

{
  "Message": "The requested resource does not support http method 'PUT'."
}
```

**Comment by davidebbo** [comment]
Talking to others, the issue may be that you are trying to PUT to `…/hybridconnection` which is not valid. You need to do a PUT to `…/hybridconnection/{hcname}` instead.

**Comment by initparam** [comment]
I tried what you the suggestion, using a fake {hcname}, just for curiousity and i got to add the HybridConnection and it now looks like what it would look like when configured via the Portal under hybridconnection. which is great!
but my fake {hcname} does not get passed to the configuration, which means that a workaround to make the API able to apply it, is via just giving it a name.
i can also see that i am having difficulities removing the configuration, because i cannot target the {hcname} under hybdrid Connections - so when trying to empty the configuration targeting the hybridconnection i get PUT Method not supported again.
but we have now found a way to be able to create the configuration, which is really good! :)

**Comment by davidebbo** [comment]
I've asked to hybrid connection experts to take a look, as I'm not very familiar with it. Note that Resource Explorer is a pretty low level tool, and has very little knowledge about any specific API. It's all metadata driven.

**Comment by initparam** [comment]
Are there any updates on this? :)

**Comment by davidebbo** [comment]
I pinged the experts again. Note that this is more of a general question about the hybrid connection API than something specifically related to Resource Explore, so it is not the best place to give it visibility. The [Azure Web App forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview) might be best.

**Comment by initparam** [comment]
ok, thank you for the help which was really usefull :)

**Comment by Zazcallabah** [comment]
I had the exact same problem, and this post helped me solve it.

The following commands worked for me:

In order to figure out the properites to use, I fetch the data from an existing website using hybrid connections:

    $data = Get-AzureRmResource -ResourceName $webAppName -ResourceType "Microsoft.Web/sites/hybridconnection" -ResourceGroupName $resourceGroupName -ApiVersion "2016-08-01"


Looking at the array $data.Properties to find the values for the $properties variable

    $properties = @{
        "entityName"="name";
        "entityConnectionString"="Endpoint=hc://name.hybrid.biztalk.windows.net/name;SharedAccessKeyName=;SharedAccessKey=key";
        "resourceType"="";
        "resourceConnectionString"="";
        "hostname"="name.local";
        "port"=80;
        "biztalkUri"="/subscriptions/guid/resourceGroups/resourcegroupname/providers/Microsoft.BizTalkServices/BizTalk/name/HybridConnection/name";
    }

The following command can then set the hybrid connection to another web site. The values doesnt seem to change, so the properties object can be stored indefinitely it seems.

    Set-AzureRmResource -ResourceName $otherWebAppName -ResourceType "Microsoft.Web/sites/hybridconnection/$($properties.entityName)" -ResourceGroupName $otherResourceGroupName -ApiVersion "2016-08-01" -Force -Properties $properties

**Comment by davidebbo** [comment]
@Zazcallabah Thanks for sharing. Closing here since issue is not in Resource Explorer.
