### ISSUE TITLE
Use /resources call to detect and filter API shape per resource group

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/ARMExplorer#12]
Calling `/subscriptions/{sub}/resources?api-version=2014-04-01` returns a list of all registered resources in the sub. e.g. entries look like:

    /subscriptions/{sub}/resourceGroups/Default-Web-NorthEurope/providers/microsoft.insights/components/MvcApp
    /subscriptions/{sub}/resourceGroups/Default-Web-NorthEurope/providers/Microsoft.Web/serverFarms/DefaultServerFarm
    /subscriptions/{sub}/resourceGroups/Default-Web-NorthEurope/providers/Microsoft.Web/sites/MySite

This can be used as follows:
- the first time a subscription node is expanded, we make a request to the server, which gets the resource list for that sub, and pre-processes it into the following data structure:

```
    /subscriptions/{sub}/resourceGroups/Default-Web-NorthEurope: {
        "microsoft.insights": [
            "components"
        ],
        "Microsoft.Web": [
            "serverFarms",
            "sites"
        ]
    }
```

Then in the UI, when a specific RG is expanded, we use this data to populate the list of providers, instead of the 'global' list.

Note that in addition to this, we'll need to query the list of registered resource **types** so that we can get the correct API version. That part can be done as part of the global metadata on the first request.

**Comment by ahmelsayed** [comment]
based on our discussion and since resourceGroup names under a subscription are unique I think I will simplify the data structure to be the following per subscription


```javascript
[
    {
        name: "Default-Web-WestUS",
        providers: [
            "Microsoft.Web",
             "Microsoft.Compute"
        ]
    },
    {
        name: "Default-Web-NorthEurope",
        providers: [
            "Microsoft.insights"
        ]
    },
    ...
]
```

The client will cache it and filter the list of providers in each resource group accordingly.

**Comment by davidebbo** [comment]
Or as alternative:

```javascript
{
    "Default-Web-WestUS":  [
        "Microsoft.Web",
        "Microsoft.Compute"
    ],
    "Default-Web-NorthEurope":  [
        "Microsoft.insights"
    ]
}
```

Maybe makes it easier to find a RG by name. Anyway, your call!

**Comment by ahmelsayed** [comment]
added `api/operations/providers/{subscriptionId}` that returns the data structure [above](https://github.com/projectkudu/ARMExplorer/issues/12#issuecomment-74192918) and changes the UI to consume it for filtering resource groups

**Comment by ahmelsayed** [comment]
opening to track second level filter on collections as well.

**Comment by ahmelsayed** [comment]
so apparently `.` is valid in resourceGroup names, but it's not a valid character in a javascript property name. It still works somehow when using the object as a hash table, but it looks odd in the debugger and might break at some point.
I changed the object model to this to avoid dots in names. this will also make case insensitive matching easier

```javascript
[
    {
        name: "Default-Web-WestUS",
        providers: [{
            name: "microsoft.insights",
            collections: [
                "alretrules",
                "autoscalesettings",
                "components"
             ]
         }]
    },
    {
        name: "Default-Web-NorthEurope",
        providers: [{
            name: "Microsoft.Web",
            collections: [
                "serverFarms",
                "sites"
             ]
         }]
    },
    ...
]
```

**Comment by ahmelsayed** [comment]
well, never mind. apparently it's expected in JavaScript to access properties with dots in their names through `[]` rather than `.` notation

**Comment by ahmelsayed** [comment]
model is an all caps `Dictionary<string, Dictionary<string, HashSet<string>>>`. it looks like this

```javascript
{
DEFAULT-WEB-NORTHEUROPE: {
    MICROSOFT.CACHE: [
    "REDIS"
    ],
    MICROSOFT.CLASSICCOMPUTE: [
        "DOMAINNAMES",
        "VIRTUALMACHINES"
    ],
     MICROSOFT.INSIGHTS: [
         "ALERTRULES",
         "AUTOSCALESETTINGS",
         "COMPONENTS"
     ],
     MICROSOFT.WEB: [
         "SERVERFARMS",
         "SITES"
     ]
},
DEFAULT-WEB-WESTUS: {
    MICROSOFT.CLASSICCOMPUTE: [
        "DOMAINNAMES",
        "VIRTUALMACHINES"
    ]
},
...
```

**Comment by davidebbo** [comment]
WHY ALL CAPS? :)

**Comment by ahmelsayed** [comment]
for case insensitive matching. That was the biggest issue actually and why I kept considering other models for a while. JavaScript doesn't have a great locale story as far as I know. So instead of having to loop through all the properties every time and comparing with toUpperCase() I figures I should just send it upper case from the server.

**Comment by davidebbo** [comment]
I see. As long as we never end up displaying them that way, it's all good!
