### ISSUE TITLE
make CTRL-S execute the PUT or PATCH action

### ISSUE THREAD

**Issue by ahmelsayed** [projectkudu/ARMExplorer#120]
favor PATCH if it's there, otherwise PUT

**Comment by davidebbo** [comment]
Interesting idea.

**Comment by snobu** [comment]
Alright, so this works fine:
```
 e.commands.addCommand({
        name: 'saveItem',
        bindKey: {
            win: 'Ctrl-S',
            mac: 'Command-S',
            sender: 'editor|cli'
        },
        exec: function (env, args, request) {
            console.log('CTRL+S pressed - executing invokePutOrPath');
            invokePutOrPatch("PUT", event);
        }
});
```

But how do i tell which method is available?
So i call `invokePutOrPatch("PATCH", event)` instead.

**Comment by ahmelsayed** [comment]
event is used to find the position of the button that was clicked so pop-ups could be displayed next to that button for warnings (on DELETE it asks for confirmation, on PUT\POST\PATCH it checks the readonly state) 

You can try setting the toggle at the top to read only and see what that does. I don't know if it'll throw an error or what. I don't know how [this ](https://github.com/projectkudu/ARMExplorer/blob/master/ng/manage.ts#L1427-L1437)would behave with a KeyboardEvent.
You can pass it as null, but that will bypass the readonly check.

**Comment by snobu** [comment]
Right now It will show the popup at the current cursor position in the editor - which i believe is want we want anyway. I believe it picks up the position from the `KeyboardEvent`, this is how it looks:

![image](https://cloud.githubusercontent.com/assets/6472374/25224740/f812d512-25c7-11e7-9738-817a9d22265d.png)

I'll send a PR later today, we can talk more on that.
