### ISSUE TITLE
ProvidersList.json missing regions

### ISSUE THREAD

**Issue by stuartleeks** [projectkudu/ARMExplorer#122]
The provider list is missing recently added regions:

```json
  "UK South",
  "UK West",
  "West Central US",
  "West US 2"
```

I modified the UpdateProvidersList.ps1 to use one of my subscriptions and the new regions were listed. 

@shobak101 - can you re-run against the 'official' subscription in the script and update? :-)

**Comment by davidebbo** [comment]
Made the change. Can you check that Staging (https://resources-staging.azure.com/) looks good?

**Comment by davidebbo** [comment]
@stuartleeks did you get to try this?

**Comment by stuartleeks** [comment]
Yes, I loaded it up, but can't remember what made me notice it originally! Sorry :-(
