### ISSUE TITLE
GetTenants doesn't return display name or domain name

### ISSUE THREAD

**Issue by israels** [projectkudu/ARMExplorer#125]
The production published version hosted on resources.azure.com renders multiple tenants which my login is associated with.  The drop down shows multiple tenants I can switch contexts for and obtain a token for them.

However, when I run the code locally, it only returns the tenantID / guids and no friendly or readable identifier.  Under the hood, it looks like the data comes from https://management.azure.com/tenants endpoint, so it's not clear where the display name or domain data is coming from.  The /tenants endpoint doesn't include that data.

**Comment by davidebbo** [comment]
Right, I think there was a reason why this didn't work locally. Note that running locally is just for dev purpose, so I don't think it's a huge deal if we need to deal with tenant guids in that scenario.

**Comment by israels** [comment]
Thanks for the response @davidebbo.  It looks like I'm having the same issue as #57.  I'm trying to get similar behavior in an app running in Azure (not just running locally).  What I'd like to do is retrieve tenant details from ARM (if possible) rather than the Graph since querying the graph will require a separate token and hence consent.

Is there some special AAD client you are using internally which has access to tenant details from ARM as @ahmelsayed implied you were doing in your production app?  As far as I have found from documentation you can only get tenantIds from ARM and you have to get tenant names from the graph.

Ultimately, I'm just looking for a way to implement the same behavior where I can render a drop down of the logged in users tenants without having to consent access for each tenant just to render the tenant names.

**Comment by davidebbo** [comment]
Resource Explorer is registered in a special 'trusted' way with AAD that allows certain behaviors that are not normally possible. I don't know whether listing tenant names is one of them.

That might be a good generic questions for [AAD experts](https://social.msdn.microsoft.com/forums/azure/en-US/home?forum=WindowsAzureAD), whether there is a supported way for a normal app to do this.

**Comment by davidebbo** [comment]
Closing as there isn't much to do here. When testing locally, we can't get the tenant names, and we can live with that.
