### ISSUE TITLE
DataLake Store Firewall Rules Powershel - wrong values

### ISSUE THREAD

**Issue by SamRakaba** [projectkudu/ARMExplorer#130]
resource explorer provided the wrong cmdlets to create a new firewall rule
-ResourceName  parameter used twice
 the correct PS command should be

# CREATE firewallRules
$ResourceLocation = "West US"
**$ResourceName = $ResourceName+"/NewfirewallRule"**
$PropertiesObject = @{
	#Property = value;
}
New-AzureRmResource -ResourceName $ResourceName -Location $ResourceLocation -PropertyObject $PropertiesObject -ResourceGroupName samtes -ResourceType Microsoft.DataLakeStore/accounts/firewallRules -ApiVersion 2015-10-01-preview -Force

**Comment by davidebbo** [comment]
Can you paste the complete command line that it gave you?

**Comment by SamRakaba** [comment]
Hi David

Here’s the command I got from resource explorer

# CREATE firewallRules
$ResourceLocation = "West US"
$ResourceName = "NewfirewallRule"
$PropertiesObject = @{
              #Property = value;
}
New-AzureRmResource -ResourceName $ResourceName -Location $ResourceLocation -PropertyObject $PropertiesObject -ResourceGroupName samtes -ResourceType Microsoft.DataLakeStore/accounts/firewallRules -ResourceName samdltest1 -ApiVersion 2015-10-01-preview -Force

And I provided the working sample

Thanks
Sam

**Comment by davidebbo** [comment]
That's odd. I don't have any DataLake resources to try this on, but it doesn't seem to happen on other resource types that I tried.

**Comment by SamRakaba** [comment]
Actually the whole datalake store section for the firewall PS cmdlets are wrong the first command to get the firewall rule the parameter “isCollection” is not a valid parameter and it errors out

PS C:\> Get-AzureRmResource -ResourceGroupName samtes -ResourceType Microsoft.DataLakeStore/accounts/firewallRules -ResourceName samdltest1 -isCollection -ApiVersion 2015-10-01-preview
Get-AzureRmResource : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Get-AzureRmResource -ResourceGroupName samtes -ResourceType Microsoft ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AzureRmResource], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet

Here’s the original


# PowerShell equivalent script

# GET firewallRules
Get-AzureRmResource -ResourceGroupName samtes -ResourceType Microsoft.DataLakeStore/accounts/firewallRules -ResourceName samdltest1 -isCollection -ApiVersion 2015-10-01-preview



# CREATE firewallRules
$ResourceLocation = "West US"
$ResourceName = "NewfirewallRule"
$PropertiesObject = @{
              #Property = value;
}
New-AzureRmResource -ResourceName $ResourceName -Location $ResourceLocation -PropertyObject $PropertiesObject -ResourceGroupName samtes -ResourceType Microsoft.DataLakeStore/accounts/firewallRules -ResourceName samdltest1 -ApiVersion 2015-10-01-preview -Force

**Comment by davidebbo** [comment]
We might need to review how the PowerShell commands are generated, as things may have changed since we first did it. Note that this could take a while, as there is very limited resources to work on Explorer.

**Comment by SamRakaba** [comment]
Thanks ,

Just wanted to bring this to your attention so no one else spends time to figure out why it is not working.

I got it to do what I needed


Thanks

**Comment by davidebbo** [comment]
Side note: all your entries on GitHub include the previous message (I manually edited a few of them). It's best to add comments only via GitHub UI to avoid this (email bridge is very broken). Thanks!

**Comment by davidebbo** [comment]
Actually, I just realized that this is already tracked by #117
