### ISSUE TITLE
Azure Resource Explorer - unable to see the JSoN for Logic App Diagnostics config

### ISSUE THREAD

**Issue by Mo-EHI** [projectkudu/ARMExplorer#134]
We have configured one of our logic apps to emit telemetry to a storage account and event hub. However when reviewing the associated JSoN via the Azure resource explorer it's not clear where to look to get the JSoN for the diagnostics config. It does not seem to be available anywhere within the resources listed under the container resource group node in the portal.

**Comment by davidebbo** [comment]
Can you clarify what the full ARM path is to the resource you are trying to get at?

**Comment by davidebbo** [comment]
I've added the latest Logic App swagger (https://github.com/Azure/azure-rest-api-specs/blob/master/arm-logic/2016-06-01/swagger/logic.json) to Resource Explorer, so it should support what's in there. If what you're looking for is not in there, it's likely not a Resource Explorer issue.

**Comment by Mo-EHI** [comment]
Hi there David,

Many thanks for picking this support request up so responsively. And apologies for the slightly belated response. The issue I have is that we have a logic which we've set up to emit diagnostic telemetry to storage and and event hub.

This can be easily done from the Aure portal; however we wish to do this using ARM template definition from That makes up the LogicApp. I've found the following link:

https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-enable-diagnostic-logs-using-template

However when I try and explore my resource group containing the concerned LogicApp using the Azure Resurce Explorer I can't see where to source that diagnostic JSoN from. I'm happy and able to craft the required JSoN; but was concerned I couldn't see the definition of my diagnostic configuration even thoguht it is clearly in place and functioning. Does that help to clarify what I'm after? To confirm, this rmains the case even after the Swagger changes you've applied recently.

**Comment by davidebbo** [comment]
@Mo-EHI I'm not familiar with the specific APIs you are looking for. To be clear Resource Explorer itself has no knowledge of any specific APIs, as it gets all its knowledge from swagger files.

So you should use the following process to investigate:

- First, find out what ARM API you are wanting to use. Ask on the forum related to the specific technology if needed.
- If you don't see that API in Resource Explorer, let me know here and we can investigate why. e.g. it could be missing from the swagger.
