### ISSUE TITLE
No `/locations` endpoint shown

### ISSUE THREAD

**Issue by duncansmart** [projectkudu/ARMExplorer#139]
Apparently (according to [this](https://github.com/Azure/azure-xplat-cli/issues/2021)) there is a locations API at `GET https://management.azure.com/subscriptions/{subscriptionId}/locations?api-version=2016-09-01` but I don't see this in ARM Explorer's treeview.

**Comment by davidebbo** [comment]
Can you try https://resources-staging.azure.com/? I'll later swap to Prod.

**Comment by duncansmart** [comment]
:+1:  Works - cheers!

**Comment by davidebbo** [comment]
Ok, it's in Prod! Thanks for the suggestion.
