### ISSUE TITLE
Plain text secrets stored in ARMExplorer during deployments

### ISSUE THREAD

**Issue by TechnologyAnimal** [projectkudu/ARMExplorer#140]
Resources that require secrets to deploy with ARM templates are displaying those in plain-text in resource explorer.  To confirm, please navigate to /subscriptions/$subscriptionId/resourceGroups/$resourceGroup/deployments?api-version=2015-11-01, on any deployment that contains plain text secrets.

Here are some examples resources that I've deployed experiencing the issue described above:

1.  API Management
2.  Application Gateway
3.  Application Service Environments

Thank you.

**Comment by davidebbo** [comment]
@TechnologyAnimal I think you are misunderstanding what Resource Explorer is. It doesn't store anything at all. All it does is call ARM APIs on user's behalf, and shows you whatever they return.

**Comment by TechnologyAnimal** [comment]
@davidebbo , long story short, I opened up a ticket about this with a premium support contract.  The support professional asked me a few questions and then asked me to open up a case here.  Can you please explain to me what product this security hole exists in or which team would be responsible?  I am just looking to get a ticket routed to the right spot.

To provide a little bit more clarity on the issue with an example.  If I want to deploy an instance of APIM with an ARM template, that deployment is logged under the uri I provided above.  Some parameters include passwords for SSL certificates, etc.  When using ARM, those secrets are stored in plain text.  Just because someone has access to APIM doesn't mean that they should have certificate passwords, for example.

I used APIM as an example, but this same behavior is found on other resources, such as application gateway and application service environments.  Any direction would be appreciated.  Thank you.
