### ISSUE TITLE
ResourceExplorer not displaying all the VMSS resources

### ISSUE THREAD

**Issue by MukeshNandaMS** [projectkudu/ARMExplorer#141]
Have a customer who has around 200+ VM's, and 70+ VMSS instances. They extensively use ResourceExplorer to manage the VMSS instances. They are facing below two issues:
1. For some of the scale sets,they are not able to find in the Resource Explorer. These VMSS are visible from Portal. If they manually browse on the left pane in Resources.Azure.com, they do not see any 'VirtualMachineScaleSets' under 'Microsoft.Compute'. This is seen for around 8-10 VMSS among 79 they have.
2. Why they are not able to see all the VMSS resources as a search help/hint when they type in the name of the ScaleSet. For manually browsing they need to remember the RG for ~80 VMSS deployments they have.

Would appreciate any pointers or inputs.

**Comment by davidebbo** [comment]
It could be an RP issue. Resource Explorer just reflects what the ARM API returns.

One thing to check for: query

    get https://management.azure.com/subscriptions/{yoursub}/resources?api-version=2017-05-10

Do this either using armclient or https://resources.azure.com/raw/. Then check if the ‘missing’ resources show up in that list. If they don’t, then it's likely a VM/VMSS RP issue.
