### ISSUE TITLE
Providers list under a subscription is incomplete

### ISSUE THREAD

**Issue by clamanna** [projectkudu/ARMExplorer#16]
The providers list under my subscription is incomplete; it is not showing all the various providers that are available. Curiously, the providers list under the resource groups is exhaustive. 

![providers-list](https://cloud.githubusercontent.com/assets/894674/6198041/7b4604ae-b3a6-11e4-994c-2853a093b44b.png)

**Comment by davidebbo** [comment]
We have some amount of confusion on the providers that are registered at the various levels. I think in some cases it's may be due to some incorrect registration. And we probably have bugs consuming it too :)
