### ISSUE TITLE
Ability to export as ARM Template

### ISSUE THREAD

**Issue by btardif** [projectkudu/ARMExplorer#21]
Would be really cool if we could stand at either a Resource Group or a specific resource and export it as a ARM template.

**Comment by davidebbo** [comment]
That would require ARM functionality that I don't believe exists today. If that becomes available and there is an ARM API to create a template from a resource group, it would become easy to expose (and I assume Preview portal would expose it as well). /cc @clamanna

**Comment by jhenriks79** [comment]
What if you created an export that just follows the same structure that exists in ARMExplorer?  You could click something like 'Recursive' and it would show JSON for the resource group as well as all the underlying services associated with the Resource Group.

**Comment by davidebbo** [comment]
I think that theoretically, it would be possible to follow the hierarchy and create an ARM template for all the resources in a Resource Group. But that's non-trivial and I would much prefer for this to happen directly in the ARM engine. I believe this is planned, though I will need to check.

**Comment by davidebbo** [comment]
This is a core ARM feature that will come later, and will not be Explorer specific. So closing here.
