### ISSUE TITLE
Figure out a story for updating the specs dlls outside of the repo

### ISSUE THREAD

**Issue by ahmelsayed** [projectkudu/ARMExplorer#28]

**Comment by davidebbo** [comment]
Two possibilities come to mind:

1. Use one region site as the master, and replicate to others (like Site Replicator)
2. Store them as blobs in some storage account, and copy down into each site

We also have to make sure this works well, in our Swap workflow. The second approach above would be much more Swap friendly, as all slots would automatically get the files.

If only we could mount an Azure File drive into Websites...

**Comment by ahmelsayed** [comment]
also ideally we won't do [non-async IO operations](https://github.com/projectkudu/ARMExplorer/blob/23d4e49e5614c3029fde9f6cc6c2b9aed12e101a/Controllers/OperationController.cs#L31-L32) on every request for metadata, so we will either need to cache the assemblies and restart the site if we add move, or setup a `FileSystemWatcher`

**Comment by shobak101** [comment]
submodule added to git repo to fix the issue
