### ISSUE TITLE
when selecting on the left tree different nodes do not change currently selected tab on right

### ISSUE THREAD

**Issue by galcho** [projectkudu/ARMExplorer#30]

**Comment by davidebbo** [comment]
Problem is that you can end up on a disabled tab. e.g.
- select 'sites' node
- go to Create tab
- now go to an existing site

Result: you're still on Create, showing blank:

![image](https://cloud.githubusercontent.com/assets/556238/6497247/e1c09434-c291-11e4-8880-484537b0a767.png)

Maybe need extra logic to reset to first tab if current is disabled?

**Comment by ahmelsayed** [comment]
That's why I had the switch to first tab originally, but then I thought maybe it's not too bad to get an empty tab as that's what you would expect.

**Comment by davidebbo** [comment]
Not sure, seems quirky to reach a normally 'impossible' state.

**Comment by ahmelsayed** [comment]
I guess the options are:

* always switch **(what we had)**
* always don't switch **(what's in dc513a9177b717dfcbfe7f56877976b6eb0759b5)**
* only switch if the current tab is disabled.

The code change for the third option is simple, but I was worried that having many little different behaviors in the UI might be confusing from the end users point of view on when to expect things to change or not change.

**Comment by davidebbo** [comment]
Ok, seems like a good middle ground!
