### ISSUE TITLE
A way to search or filter in the left menu

### ISSUE THREAD

**Issue by fashaikh** [projectkudu/ARMExplorer#35]
Some user accounts have multiple resources, and drilling through can be time consuming. This'll be a quick way to narrow the set of things to work with

**Comment by ahmelsayed** [comment]
@shrimpy had an idea of supporting search by relying on CSM's `/resources`. We can track it in here.

**Comment by shrimpy** [comment]
Fixes in 9002ac1dc54b26d4e6909c3854bbdfeda06a3b66
