### ISSUE TITLE
Metadata doesn't account for resource types that not all users have

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/ARMExplorer#38]
We can the metadata from the first user. If the second user has additional providers they're registered with, we don't have the metadata for them.

**Comment by ahmelsayed** [comment]
a quick test between caching and not caching the metadata on the server comes to ~700ms vs ~20ms. It's probably not that big of a deal. I can turn off the caching and see if we start to notice slowness.

**Comment by davidebbo** [comment]
@shobak101 isn't this already fixed since we precompute the metadata now?

**Comment by shobak101** [comment]
yes commit 6ed86d91139a59b83b75cb6f22121a7de74eb996 , I did not link it to the issue back then sorry
