### ISSUE TITLE
Read Only Mode 

### ISSUE THREAD

**Issue by ahmelsayed** [projectkudu/ARMExplorer#4]
Support setting the whole portal in a ReadOnlyMode where no PUT, POST, or DELETE operations are allowed.

**Comment by davidebbo** [comment]
Minor bug: clicking Delete first prompts you to confirm, and then tells you that you can't do it. But really, that's no big deal.

**Comment by ahmelsayed** [comment]
It should be fixed now. Also will not display the error sign since it doesn't make sense as well.
