### ISSUE TITLE
Copy to clipboard button for those text areas

### ISSUE THREAD

**Issue by suwatch** [projectkudu/ARMExplorer#41]
Often time I need to copy content and paste somewhere else, it is not easy to do so.   Ctrl-A doesn't work as I want - it selects everything.   If we could support Ctrl-A, Ctrl-C and Ctrl-V, that would do too.

**Comment by snobu** [comment]
I'll "rehydrate" (it's really more like resurrect) this thread for this small request:

![image](https://cloud.githubusercontent.com/assets/6472374/24899722/fa9d5156-1ea9-11e7-8a0f-4be46a4a2333.png)

I think that little button will save a lot of people a lot of minutes every week. Or maybe it's just me that needs it?.. 

I'm assuming this is the angular _thing_ we need to pull in?
https://sachinchoolur.github.io/ngclipboard/

**Comment by davidebbo** [comment]
I'm all for adding a Clipboard button. @ahmelsayed can probably comment whether that's the right Angular thing to use. We have Copy buttons in Function Portal.

**Comment by ahmelsayed** [comment]
You probably don't need anything fancy like that. Just a button or a clickable with a handler that goes [here](https://github.com/projectkudu/ARMExplorer/blob/master/index.html#L113) 
```html
<i class="fa fa-copy" ng-click="copyToClipboard(selectedResource.url + '?api-version=' + apiVersion)"></i>
```

and the code itself is pretty easy (IE not supported)

```typescript
//https://www.reddit.com/r/web_design/comments/33kxgf/javascript_copying_to_clipboard_is_easier_than
$scope.copyToClipboard = (text: string) => {
    var textField = document.createElement('textarea');
    textField.innerText = text;
    document.body.appendChild(textField);
    textField.select();
    document.execCommand('copy');
    textField.remove();
}
```

What's actually hard is getting the layout to cooperate :) All the buttons to the right of the url are `float: left`, and the url itself is a block. You'll probably need to change the layout for that whole section.

**Comment by snobu** [comment]
You're scaring me :) I'll give this a go anyway.

**Comment by ahmelsayed** [comment]
Yeah sorry the css in this project is a bit of a mess :) I'm not very good with css

![](http://i.imgur.com/Q3cUg29.gif)

**Comment by snobu** [comment]
Not very happy yet with the result but it's getting somewhere.

![image](https://cloud.githubusercontent.com/assets/6472374/24965364/b26067ca-1f58-11e7-877b-719a1c1a558a.png)

I think we're running out of horizontal space on that line. It looks a bit better with the URL on the next line in my opinion - what do you think?

![image](https://cloud.githubusercontent.com/assets/6472374/24965664/8f3cb180-1f59-11e7-9153-4fcc78a47264.png)

You'll notice that i'm very picky about my CSS, of which i know very little!

**Comment by ahmelsayed** [comment]
I don't have strong opinion either way, though I slightly prefer the first one. @davidebbo what do you think?

**Comment by davidebbo** [comment]
Yes, 1st one so we don't waste an extra line of display.

**Comment by snobu** [comment]
![copy](https://cloud.githubusercontent.com/assets/6472374/25000463/170d3b70-204a-11e7-8508-c3003c195af9.gif)

Alright, tried to keep it really simple. The feedback is given by the URL flashing green (implemented with a $timeout between green and the default color in `ng-style`).

**manage.ts**:
```typescript
    $scope.copyToClipboard = (text: string) => {
        var textField = document.createElement('textarea');
        textField.innerText = text;
        document.body.appendChild(textField);
        textField.select();
        document.execCommand('copy');
        // Cycle resource URL color for visual feedback
        $scope.resUrlColor = '#718c00'; // a soft green
        $timeout(function () {
            $scope.resUrlColor = '#000';
        }, 700);
        textField.remove();
    }
```

Good enough for PR?

**Comment by davidebbo** [comment]
Works for me!

**Comment by ahmelsayed** [comment]
looks good to me too 👍
