### ISSUE TITLE
Support AD directory in path

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/ARMExplorer#45]
e.g. it could support `https://resources.azure.com/microsoft.com/subscriptions/etc...` to make the directory explicit.

**Comment by ahmelsayed** [comment]
When the user is initially logging in, they will log into their default directory, that is whichever one AAD picks for them.
After that if we have a deep link, we will query ARM for the tenant Id for the given subscription. ARM has mapping of subscriptionId <-> tenantId, for all Azure Subscriptions.

- If it's the same as the current tenantId, nothing to do, proceed with existing deep link logic.
- If not, save the deep link, redirect to the correct tenant, redirect back to explorer, extract the saved deep link, and proceed as before

**Comment by suwatch** [comment]
We don't have too.  The subscriptionId and tenantId are dependent and, given subscriptionId, there is a very quick and unauthenticated way to find out tenantId - little to no perf.   It will require at most one redirect to get the token (which is the same for Portal).   Having both in deep link is unnecessarily redundant.

**Comment by davidebbo** [comment]
Ok, closing as this appears unnecessary.
