### ISSUE TITLE
Service Management API support?

### ISSUE THREAD

**Issue by robrich** [projectkudu/ARMExplorer#50]
This is a phenomenal product.  Well done.

Is there a similar experience for the Service Management API (original portal)?  E.g. the https://{bla}.blob.core.windows.net/ API documented at https://msdn.microsoft.com/en-us/library/azure/ee460799.aspx ?  I can't seem to discover how to start up / shut down VMs in the Microsoft.ClassicCompute/virtualMachines nodes in the same way I see at https://msdn.microsoft.com/library/azure/jj157189.aspx.

**Comment by davidebbo** [comment]
Thanks for the feedback!

Sorry, it is only targeted at the new ARM API. I'm not a VM expert, but I think the plan is that there will soon be a new compute ARM API that supports everything (to replace the 'classic' API).
