### ISSUE TITLE
Problems when receiving the tenantID 

### ISSUE THREAD

**Issue by uvirk** [projectkudu/ARMExplorer#57]
In the ARMExplorer.cs,  specifically using this code:

```
  private JArray ToTenantDetails(JArray tenants)
        {
            var result = new JArray();
            foreach (var tenant in tenants)
            {
                var value = new JObject();
                value["DisplayName"] = tenant["tenantId"];
                value["DomainName"] = tenant["tenantId"];
                value["TenantId"] = tenant["tenantId"];
                result.Add(value);
            }
            return result;
        };


# Issue
The DisplayName, DomainName, and TenantID are all set to the "TenantId", which, in my case is a GUID. I am having trouble retrieving Both the DisplayName and DomainName.

**Comment by davidebbo** [comment]
Are you describing an issue you see on https://resources.azure.com/, or when running locally? When running locally, I think it's a known limitation. But since it's just for development purpose, we can live with that.

**Comment by uvirk** [comment]
Hey David, Thanks for the response. The problem is when running locally. How would I deal with the problem of the GUID showing in the dropdown that that function is used for?

**Comment by ahmelsayed** [comment]
Hi @uvirk,

In your own app, when you send a request to `GET https://graph.windows.net/{tenantId}/tenantDetails/?api-version=1.5`, you'll get back an object that looks like this

```json

{
  "odata.metadata": "https://graph.windows.net/{tenantId}/$metadata#directoryObjects/Microsoft.DirectoryServices.TenantDetail",
  "value": [
    {
      "odata.type": "Microsoft.DirectoryServices.TenantDetail",
      "objectType": "Company",
      "objectId": "{tenantId}", //this is the GUID we're using
      "deletionTimestamp": null,
      "assignedPlans": [],
      "city": null,
      "companyLastDirSyncTime": null,
      "country": null,
      "countryLetterCode": "",
      "dirSyncEnabled": null,
      "displayName": "{displayName}", //this is what you're looking for
      "marketingNotificationEmails": [],
      "postalCode": null,
      "preferredLanguage": "en",
      "provisionedPlans": [],
      "provisioningErrors": [],
      "securityComplianceNotificationMails": [],
      "securityComplianceNotificationPhones": [],
      "state": null,
      "street": null,
      "technicalNotificationMails": [],
      "telephoneNumber": null,
      "verifiedDomains": []
    }
  ]
}

```


actually I think we can fix it here as well to show the name even when running locally. I'll take a look at that

**Comment by ahmelsayed** [comment]
btw, in the code snippet you have in the original issue, we are asking ARM for the tenant details rather than AAD Graph.
The ARM call is `GET https://management.azure.com/tenants?api-version=2014-04-01` which returns a response that looks like this

```json

{
  "value": [
    {
      "id": "/tenants/{tenantId}",
      "tenantId": "{tenantId}"
    },
    {
      "id": "/tenants/{tenantId}",
      "tenantId": "{tenantId}"
    },
    ...
  ]
}

```

one problem in calling Graph rather than ARM is that the token you'll be using for ARM doesn't work with Graph. You need to get a new token for graph.

**Comment by uvirk** [comment]
Hey @ahmelsayed thanks for the response!
