### ISSUE TITLE
Can't create a new website

### ISSUE THREAD

**Issue by pawelpabich** [projectkudu/ARMExplorer#59]
Hi,

I can retrieve data of an existing web site but I can not create a new one. The create button is disabled.
I'm sure this worked for me before :(.

![image1](https://cloud.githubusercontent.com/assets/347637/8298451/5da375dc-19ac-11e5-865c-2e18ee153fd9.jpg)

**Comment by davidebbo** [comment]
Nice screenshot :)

Your looking at a new node that shows all sites in a subscription and that didn't exist before. To create a site, you need to go under a specific resource group.

**Comment by pawelpabich** [comment]
:)

Thanks! That was it. I think I used ARM before without resource groups. It might be a good idea to add a message with an explanation why something is disabled.

**Comment by davidebbo** [comment]
Agreed. Though it's all metadata driven, so the most we could say is "this collection is not updatable", which is not all that helpful...

**Comment by pawelpabich** [comment]
Yeah, some layer of "user friendliness" would be nice to have :)
