### ISSUE TITLE
PowerShell: remove line numbers

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/ARMExplorer#63]

**Comment by shobak101** [comment]
Done and live in Staging

**Comment by davidebbo** [comment]
I'm still seeing line numbers. Maybe that got regressed?

**Comment by davidebbo** [comment]
@shobak101 was was the commit ID for previous change? It's good to have it in issue when closing it, for later reference. Thanks!

**Comment by shobak101** [comment]
closed with this commit 
0f888016569ca2f2e1ca1f6038d41ca4cfda2ba0
