### ISSUE TITLE
PowerShell: collection call missing -IsCollection param

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/ARMExplorer#77]
e.g. when on a site list, it gives:

```PowerShell
# GET sites
Get-AzureResource -ResourceGroupName Default-Web-NorthEurope -ResourceType Microsoft.Web/sites -OutputObjectFormat New -ApiVersion 2015-08-01
```

This blows up because it tries to hit the base resource API with the version that's meant for the websites RP. Simplest fix is to pass `-IsCollection` flag to hit the RP instead of ARM cache.

**Comment by shobak101** [comment]
cb00cb297d6e75727fd9df4771cc1039395556b6
