### ISSUE TITLE
YOU FOLKS ARE DOING TREMENDOUS JOB, SERIOUSLY, ITS VERY COOL AND USER FRIENDLY IDEA BEHIND ALL THIS ...

### ISSUE THREAD

**Issue by shimail1** [projectkudu/ARMExplorer#78]
CONGRATS....

YOU FOLKS ARE DOING TREMENDOUS JOB, SERIOUSLY, ITS VERY COOL AND USER FRIENDLY IDEA BEHIND ALL THIS ...

LOOKING FORWARD FOR MORE SOON , ALREADY A GREAT JOB

**Comment by davidebbo** [comment]
Thanks for the feedback!
