### ISSUE TITLE
Can't get Edit button

### ISSUE THREAD

**Issue by DharmeshSolanki7** [projectkudu/ARMExplorer#90]
I can't find Edit button for editing any of my resources with resource explorer. can you please suggest and help to resolve it. 

Thanks.

**Comment by davidebbo** [comment]
Can you please be mor specific about exactly what scenario you are trying? e.g. try going to a Web App (aka Websites) and see if you have the button there. If you don't please include screenshot.

**Comment by DharmeshSolanki7** [comment]
Hi David,

Thanks for your response.

Whenever I am trying to access the and edit something in resource explorer, I can’t get the EDIT button(just GET button). Due to that I can’t edit anything.

Below is the snap for the same.

[cid:image001.png@01D1130A.51D9E450]


[cid:image002.png@01D1130A.51D9E450]

Please help to resolve this.

Thanks.

Best Regards,

Dharmesh Solanki

**Comment by davidebbo** [comment]
Your images didn't work. Also, please clarify whether you tried this specifically for a Web App, per my previous question.

**Comment by davidebbo** [comment]
One more thing: please do not reply via email, as it works poorly as you can see above. You need to respond from the GitHub site.

**Comment by DharmeshSolanki7** [comment]
HI David,

I am reaching to websites (resources.azure.com) and after that approaching my subscription and then to virtual machine for editing. But facing the issue over there. 
Please find the below snap

![1](https://cloud.githubusercontent.com/assets/15375638/10866889/c837e80c-8080-11e5-84ce-96d539be8e05.PNG)

Please let me know if you need any other details from me. 
Thanks,
Dharmesh

**Comment by DharmeshSolanki7** [comment]
No Edit button over there. I want EDIT button to make edition over template to make further deployment.

Thanks.

**Comment by davidebbo** [comment]
Hard to say without seeing more of where you are in the tree. e.g. are you sure you're looking at an individual VM and not the collection of VMs? Collections are not editable.

**Comment by DharmeshSolanki7** [comment]
Seems you are correct, by mistake i am looking at collection of VM, Just now seen that i can see edit button under Resource group and Web.

Thanks for the guidance.
