### ISSUE TITLE
Handle resource URLs with '#' signs

### ISSUE THREAD

**Issue by duncansmart** [projectkudu/ARMExplorer#97]
I uploaded a certificate recently which ended up getting the auto-generated name something like `B1F51237BB9640557BECCAAD441E8E8338E1C091##North Europe#northeuropewebspace` (note the `#` signs). When I click the certificate node in ARMExplorer I end up getting the error:

    {
      "data": {
        "error": {
          "code": "MissingApiVersionParameter",
          "message": "The api-version query parameter (?api-version=) is required for all requests."
        }
      },
      "status": 400
    }

I expect that ARMExplorer is parsing the URL at some point and the `##North Europe#northeuropewebspace` is being treated as a URL fragment and not being passed to the management.azure.com backend. Fiddler monitoring what the .NET library Microsoft.Azure.Management.WebSites library does ([see here](https://github.com/Azure/azure-sdk-for-net/blob/master/src/ResourceManagement/ApiManagement/ApiManagementManagement/Generated/CertificatesOperations.cs#L140)) , the URL parts should be encoded like so (it uses  Uri.EscapeDataString on each part of the path): 

    B1F51237BB9640557BECCAAD441E8E8338E1C091%23%23North%20Europe%23northeuropewebspace

So the final URL would be:

    https://management.azure.com/subscriptions/MYSUBSCRIPTIONID/resourceGroups/MYRESOURCEGROUP/providers/Microsoft.Web/certificates/B1F51237BB9640557BECCAAD441E8E8338E1C091%23%23North%20Europe%23northeuropewebspace?api-version=2015-08-01

**Comment by snobu** [comment]
```csharp
url = url + Uri.EscapeDataString(certificateId);
```
`Uri.EscapeDataString` follows  [RFC2396](https://www.ietf.org/rfc/rfc2396.txt "RFC2396") which states:

> The angle-bracket "<" and ">" and double-quote (") characters are
   excluded because they are often used as the delimiters around URI in
   text documents and protocol fields.  __The character "#" is excluded
   because it is used to delimit a URI from a fragment identifier__ in URI
   references (Section 4). The percent character "%" is excluded because
   it is used for the encoding of escaped characters.
```
   delims      = "<" | ">" | "#" | "%" | <">
```

We would need a custom `EscapeDataString` for this special case.

Not sure who is generating that cert name, is it Azure/ARMExplorer or a combination of that + user given name?

**Comment by duncansmart** [comment]
Yes `#` is a poor choice for a delimiter and ultimately whoever is generating that should use something a bit safer/saner, but these resource IDs are out there now :cry:

FYI `EscapeDataString` does encode `#`: 

    > Console.Write(Uri.EscapeDataString("#"));
    %23

I wonder if splitting the path on `/` and encoding each part (or just the last component) once would suffice.

**Comment by snobu** [comment]
Hmm.. Looks like i'm unable to repro this on http://resources.azure.com

![image](https://cloud.githubusercontent.com/assets/6472374/12554860/2098354e-c387-11e5-86ef-ea10e1d190d7.png)

What are the steps to do a repro?

**Comment by duncansmart** [comment]
yep, beat me to it :smile:

**Comment by snobu** [comment]
> I expect that ARMExplorer is parsing the URL at some point and the `##North Europe#northeuropewebspace` is being treated as a URL fragment and not being passed to the management.azure.com backend.

Not really. What you see in the right pane is the raw JSON we get from __management.azure.com__. And that's what we POST back when you click on the individual cert.

Unsure how to approach this frankly, let's wait for the people who actually contributed code to this project to chip in, i'm pretty new around here (An ARMExplorer n00b to be precise).

**Comment by davidebbo** [comment]
So it sounds like if the ARM ID has some `#` chars, they need to be escaped before calling ARM? Have you verified that this in fact works, e.g. using [ARMClient](https://github.com/projectkudu/ARMClient)? /cc @shobak101

**Comment by snobu** [comment]
##### With `#` in URI (Getting 400 BadRequest) #####
```
C:\>armclient get "https://management.azure.com/subscriptions/xxxxxx-xxxxxx-xxxxxx-xxxxxx/resourceGroups/ps2-onpre-tests/providers/Microsoft.Web/certificates/7152A8838E585BBDFBDBF57C32370B9BD9C73680##North Europe#ps2-onpre-tests-NorthEuropewebspace?api-version=2015-08-01" -verbose
---------- Request -----------------------

GET /subscriptions/xxxxxx-xxxxxx-xxxxxx-xxxxxx/resourceGroups/ps2-onpre-tests/providers/Microsoft.Web/certificates/7152A8838E585BBDFBDBF57C32370B9BD9C73680 HTTP/1.1
Host: management.azure.com
Authorization: Bearer eyJxxxxxxxxxx...
User-Agent: ARMClient/1.1.1.0
Accept: application/json
x-ms-request-id: 665cfc2b-a974-4b7d-b481-9746b6ee50d3


---------- Response (439 ms) ------------

HTTP/1.1 400 BadRequest
Pragma: no-cache
x-ms-failure-cause: gateway
x-ms-request-id: 201ec25b-7e04-4b95-bd84-57bd6ada8b48
x-ms-correlation-request-id: 201ec25b-7e04-4b95-bd84-57bd6ada8b48
x-ms-routing-request-id: WESTEUROPE:20160125T223650Z:201ec25b-7e04-4b95-bd84-57bd6ada8b48
Strict-Transport-Security: max-age=31536000; includeSubDomains
Cache-Control: no-cache
Date: Mon, 25 Jan 2016 22:36:50 GMT

{
  "error": {
    "code": "MissingApiVersionParameter",
    "message": "The api-version query parameter (?api-version=) is required for all requests."
  }
}
```



##### With `%23` instead of `#` (Getting 200 OK) #####
```
C:\>armclient get "https://management.azure.com/subscriptions/xxxxxx-xxxxxx-xxxxxx-xxxxxx/resourceGroups/ps2-onpre-tests/providers/Microsoft.Web/certificates/7152A8838E585BBDFBDBF57C32370B9BD9C73680%23%23North Europe%23ps2-onpre-tests-NorthEuropewebspace?api-version=2015-08-01" -verbose
---------- Request -----------------------

GET /subscriptions/xxxxxx-xxxxxx-xxxxxx-xxxxxx/resourceGroups/ps2-onpre-tests/providers/Microsoft.Web/certificates/7152A8838E585BBDFBDBF57C32370B9BD9C73680%23%23North%20Europe%23ps2-onpre-tests-NorthEuropewebspace?api-version=2015-08-01 HTTP/1.1
Host: management.azure.com
Authorization: Bearer eyJxxxxxxxxxx...
User-Agent: ARMClient/1.1.1.0
Accept: application/json
x-ms-request-id: e1caf070-40a5-4ae0-ae42-f13a2ac76112


---------- Response (1453 ms) ------------

HTTP/1.1 200 OK
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
x-ms-request-id: e1caf070-40a5-4ae0-ae42-f13a2ac76112
x-ms-ratelimit-remaining-subscription-reads: 14999
x-ms-correlation-request-id: 49886a3b-689b-40bb-a1db-2be54aed4fad
x-ms-routing-request-id: WESTEUROPE:20160125T223707Z:49886a3b-689b-40bb-a1db-2be54aed4fad
Cache-Control: no-cache
Date: Mon, 25 Jan 2016 22:37:07 GMT
Server: Microsoft-IIS/8.0
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET

{
  "id": "/subscriptions/xxxxxx-xxxxxx-xxxxxx-xxxxxx/resourceGroups/ps2-onpre-tests/providers/Microsoft.Web/certificates/7152A8838E585BBDFBDBF57C32370B9BD9C73680##North Europe#ps2-onpre-tests-NorthEuropewebspace",
  "name": "7152A8838E585BBDFBDBF57C32370B9BD9C73680##North Europe#ps2-onpre-tests-NorthEuropewebspace",
  "type": "Microsoft.Web/certificates",
  "location": "North Europe",
  "tags": null,
  "properties": {
    "friendlyName": "",
    "subjectName": "demo.cert.with.hash",
    "hostNames": [
      "demo.cert.with.hash"
    ],
    "pfxBlob": null,
    "siteName": null,
    "selfLink": null,
    "issuer": "demo.cert.with.hash",
    "issueDate": "2016-01-25T11:08:49+02:00",
    "expirationDate": "2026-01-22T11:08:49+02:00",
    "password": null,
    "thumbprint": "7152A8838E585BBDFBDBF57C32370B9BD9C73680",
    "valid": null,
    "toDelete": null,
    "cerBlob": null,
    "publicKeyHash": null,                                                                                                                                                                                                                       "hostingEnvironment": null,
    "hostingEnvironmentProfile": null,
    "keyVaultId": "",
    "keyVaultSecretName": "",                                                                                                                                                                                                                    "webSpace": "ps2-onpre-tests-NorthEuropewebspace",
    "tags": null
  }
}
```

**Comment by davidebbo** [comment]
Thanks for confirming. So it sounds like the fix is probably only server side, to escape things before calling ARM.

**Comment by shobak101** [comment]
please give it a try at resources-staging.azure.com, will swap it to prod soon.

**Comment by duncansmart** [comment]
:+1: works for me, :tada:
